### PR TITLE
print more details in example/sml_server

### PR DESCRIPTION
**Pull request by hmueller01**
After having trouble getting detailed data out of my power meter I found some examples on other projects and merged this into a new version of sml_server. I think this helps others too.

Details:
- let the serial device set on command line
- print OBIS data

### CODE REVIEW

**Comment by devZer0** [comment]
Your code is very interesting, i was working on similar one some time ago. This repo is dead, libsml is maintained by Volkszähler Community now ( http://volkszaehler.org/pipermail/volkszaehler-dev/2015-January/004064.html) , could you please resend your pull request to https://github.com/volkszaehler/libsml ? Thank you!

**Comment by hmueller01** [comment]
Thanks. Didn't know that. Bad thing at volkszaehler is that it is a fork of this and one can not know that they maintain it now. Wouldn't it be better to start new and call it libsml2 or so?

**Comment by devZer0** [comment]
good point, but it would be best if you could bring that up on vz-dev mailing list.

**Comment by devZer0** [comment]
it's not a real fork as dailab libsml is orphaned/dead end.

**Comment by hmueller01** [comment]
Patch was successfully integrated in volkszaehler fork.

**Pull request closed without merging**
